name: Build Linux Server

on:
  push:
    branches: [master]
    paths:
      - 'server/**'
      - 'web-client/**'
      - 'packaging/**'
      - '.github/workflows/build_linux.yml'
      - '.github/workflows/build_platform.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      source_sha:
        required: true
        type: string
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-x86_64:
    uses: ./.github/workflows/build_platform.yml
    with:
      platform: linux
      arch: x86_64
      runner: ubuntu-22.04
      source_sha: ${{ inputs.source_sha || github.sha }}
      version: ${{ inputs.version || '' }}
